permalink   : /:categories/:year/:title/
markdown: redcarpet
highlighter : pygments

comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Ricardo Fleury | Web Developer
description: "Ricardo Fleury is an experienced web developer with experience building mobile-ready responsive web applications for startups, small businesses, agencies, and corporate clients alike.  Core technologies used include Ruby on Rails (RoR), HTML, CSS, JavaScript.  See his client work and open source projects, along with a blog inspired by his learning process."
email: rfleury2@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ricardofleury.com"
repository: "https://github.com/rfleury2/personal-website"

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty