permalink   : /:categories/:year/:title/
# markdown    : kramdown
markdown: redcarpet
highlighter : pygments

comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Ricardo Fleury | Web Developer
description: ""
email: rfleury2@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://nandomoreira.me/lora"
# repository: "https://github.com/nandomoreirame/lora"
# disqus_shortname: "fernandomoreira"
# google_analytics: UA-52446115-1